### ISSUE TITLE
[FEATURE REQUEST] Add tooltip

### ISSUE THREAD

**Issue by jasper-jool** [fthx/simple-task-bar#1]
Would be nice to have a tooltip to distinct one app from another.

**Comment by fthx** [comment]
I agree.
I'm working on it right now.

**Comment by fthx** [comment]
Ok, done.
I find that it's a natural way to make the tooltip replacing the app menu. (+ now you have the window title in app menu instead of the app title)
https://github.com/fthx/simple-task-bar/commit/275fa4ba9f63e41fbfbca5728171ca6bee7da6aa

**Comment by jasper-jool** [comment]
Nice! When will it be available?

**Comment by fthx** [comment]
Soon, once Andy Holmes will review that.
You can right now download the files on github here or here : 
https://extensions.gnome.org/review/download/14630.shell-extension.zip
unzip it and replace the files in your local GS extensions folder, next logout/login.

**Comment by fthx** [comment]
I would be happy if you can test it. I use it at the moment, I worked on it last night and it seems fully ok, no errors in logs, no bugs at all *on my laptop*.

**Comment by jasper-jool** [comment]
No issues here so far ;-)

**Comment by fthx** [comment]
Thanks, and thanks again for giving me some work I wanted to do since some weeks without the energy to do it.

**Comment by jasper-jool** [comment]
Haha no problem, I really like the extension!

Hope it's no COVID-19 :stuck_out_tongue_closed_eyes:

**Comment by fthx** [comment]
It's because covid I can write some code since I work at home !

**Comment by jasper-jool** [comment]
Haha, it has some pro’s too ;-)
