### ISSUE TITLE
[FEATURE REQUEST] Right click menu

### ISSUE THREAD

**Issue by arterrey** [fthx/simple-task-bar#10]
Hi @fthx I made a comment in Gnome Extensions website before about drag-able icons, understand that could be a hard feature to implement.

Another thought... Perhaps if right click could revel a context menu giving options... Move to workspace 1, Move to workspace 2, Close Window etc... that could be an easier win and a step toward drag-able icons anyway.

**Comment by fthx** [comment]
Hi,

I think it's worth waiting external help or internal energy to implement dnd. It would be so much natural.

**Comment by vadbars** [comment]
I believe extension should be kept simple. Adding a right-hand menu to each app icon can make it overly complicated.

Although ... I would only add a call to the global application menu when you right-click on the first icon (the one on the far left). Left click brings up an overview of running applications, right click brings up the applications menu. It looks logical.
(I will add as a new issue)

**Comment by fthx** [comment]
After some thinking :-) I think we need dnd or nothing.
