### ISSUE TITLE
global application menu when you right-click on the first icon [feature request]

### ISSUE THREAD

**Issue by vadbars** [fthx/simple-task-bar#11]
I would only add a call to the global application menu when you right-click on the first icon (the one on the far left). Left click brings up an overview of running applications, right click brings up the applications menu. It looks logical.

**Comment by fthx** [comment]
Oh I can do that. That's exactly the idea of one of my other extensions : 
https://extensions.gnome.org/extension/2642/overview-or-applications/
I'll do it soon when I'll have some time.

**Comment by fthx** [comment]
Ok, after some thinking, I won't do that.

You can use this extension (there will be these days a settings UI by @Leleat ) with Activities button ON, and use my other extension here:
https://extensions.gnome.org/extension/2642/overview-or-applications/
(please note that this website is currently down !...)
It will fill your needs !
