### ISSUE TITLE
[FEATURE REQUEST] Settings page/more setting variables

### ISSUE THREAD

**Issue by Leleat** [fthx/simple-task-bar#12]
I read in a closed issue that you didn't plan to include a settings page for "now" (half a year ago). Did your stance on this change?

I tried using your extension but it clashes with another extension I use ("Unite"). I use Unite to add a Close button into my topbar so I can close windows with a quick wrist flick. It also disables the Window titles. Here is a screenshot with both extensions enabled.

![scr](https://user-images.githubusercontent.com/53054301/93711578-fed2e680-fb3e-11ea-998c-9e166e21b98d.png)

If I use Simple-Task-Bar, the Activities button get hidden (even if I re-enable it in Unite). Window titles will also be shown (which I tried to disable via Unite. I only wanted to see the app name). 

While you added easy-to-edit variables at the top of extension.js, my issue with Window titles doesn't seem to be one an option there. So a dedicated Settings page could help here or at least an additional variable to disable window titles.

If you do decide to add a Settings page (or more variables), here are some ideas:

- add configurable spacing between each workspace section for clearer visibility (e. g. 35 px before the [2] / after the Firefox icon in my screenshot)

- ~shortcuts for window switching within the current workspace (with wraparound) based on the currently focused window. For example: Super+Left/Right or A/D. While people can use Alt/Super+Tab, the order of it is based on recent usage and it shows all apps. So having a non-changing order (like your extension does it) could also be useful and quicker since you don't have to first search for the app in the list of all open apps.~ found an extension which disables listing of all open apps in the Alt+Tab, so this is also kinda obsolete now.

- always show the overview when switching workspaces (and not just when pressing a button on the taskbar), if no app is running on the new workspace. 

- ~disable Window titles and only show app name (or at least not forcing the Window title update)~ pr opened

- ~maybe monochrome icons (since that seems to be GNOME's default look)~ looks kinda bad

------------------------------

It's kinda redundant to have the normal Window title (menu) and your "Line" to indicate the currently focused window. How about merging these 2 (although I don't know how difficult that would be). Here is a mockup of what I mean:

![Mockup](https://user-images.githubusercontent.com/53054301/93712720-1910c280-fb47-11ea-98f0-dfd5bae95eb7.png)

[Edit]

BTW do you accept PRs? While I am only looking into learning Gnome extensions right now, adding a variable to disable the window title update seems easy to do even for a beginner.

**Comment by fthx** [comment]
Of course you can propose some PRs !
I'd like some help for monochrome icons (I did not look at how to do it) or proper settings UI.

For the window title position, putting it inside the taskbar will provoke some size issues, for sure.

I'll look at your propositions when I'll have time, maybe tuesday.

**Comment by Leleat** [comment]
I don't know how to get the symoblic icon from GNOME so I just added a desaturation effect to the icons... and it looks pretty bad. Every icon ends up looking same-y. Even with the symbolic icons, the icons may be to homogenous and hard to distinguish on a quick glance. So I think the way it is currently, is the best way after all (removed the request from my original comment).

![scr](https://user-images.githubusercontent.com/53054301/93719946-702d8c00-fb75-11ea-9930-ed3bfb87206c.png)
