### ISSUE TITLE
[BUG] Missing schmas.compiled after update

### ISSUE THREAD

**Issue by thoosen** [fthx/simple-task-bar#16]
Hi,

This morning, my system automatically updates simple-task-bar, and upon start up produced this trace:
```
GLib.FileError: Failed to open file “/home/tez/.local/share/gnome-shell/extensions/simple-task-bar@fthx/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  _init@/home/tez/.local/share/gnome-shell/extensions/simple-task-bar@fthx/prefs.js:23:48
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  buildPrefsWidget@/home/tez/.local/share/gnome-shell/extensions/simple-task-bar@fthx/prefs.js:10:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I am running Fedora 32, and Gnome 3.36.2. I pulled the extension from https://extensions.gnome.org/extension/2672/simple-task-bar/, and I use the Firefox/gnome-shell integration plugin to install and manage extensions.

In `/home/tez/.local/share/gnome-shell/extensions/simple-task-bar@fthx`, there is not even a `schemas` subdirectory. I am totally unfamiliar with Gnome Shell extension development, building, packaging. Can you advise how this can be fixed?

Your help and your extension are much appreciated. Many thanks!

**Comment by fthx** [comment]
Thanks for your BR.

Yes there was a problem: I used zip -j as usual to compress & upload the extension without noticing it does not work with subfolders. So I missed the missing schemas folder... Well.

So, the new version is here at the moment:
https://extensions.gnome.org/review/download/19362.shell-extension.zip
You can just pick the schemas folder in this GitHub repo, that's the same version. The bug was only in packaging for Gnome Extensions website.

**Comment by fthx** [comment]
You'll can enjoy the new settings UI through usual extensions way!

**Comment by thoosen** [comment]
Hello, that worked perfectly! I hope you're able to fix the build on Gnome Extensions.

**Comment by fthx** [comment]
Oh I think it will be ok once the new version is reviewed. It should happen these days, maybe faster.
https://extensions.gnome.org/review/19362
Please give a feedback about the new settings UI (wishlist, bugs, ...).

**Comment by thoosen** [comment]
Hi again. I don't really have much feedback. Now that I have this new version running, I can't really remember what was in the old settings UI and what's new. I set this up ages ago, and haven't touched the config in a while.

Regardless, I do have this to say:
- "Padding between workspaces" seems new, and it's great! I've been waiting for a way to easily discern the workspace grouping of icons.
- In a similar vein: the workspace number icons/squares look a little too much like normal application icons. Now that there's inter-group padding, this is less of an issue, but would there be a way to de-emphasize the workspace number square? I don't really have my own concrete soluton, and I like the workspace number being present, but hope that you might explore some options. Equally, this is not a major issue for me, just a nice-to-have.

Otherwise, I love this extension!

All the best.

**Comment by thoosen** [comment]
Oh, should I put the above comment in a new issue?

**Comment by fthx** [comment]
No need to open another thread. I know it's not good but I don't care. :-)

There was NO settings UI !
;-)
@leleat did this job these days.

Did you try monochrome (desaturated) icons ? What do you expect of a setting about workspace label ? An opacity setting of the number ? of the background ? both ?

**Comment by thoosen** [comment]
> There was NO settings UI !

Ha, that's probably why I don't remember it!

> Did you try monochrome (desaturated) icons ?

I did. I prefer the full-colour icons. But the setting certainly worked.

> What do you expect of a setting about workspace label ? An opacity setting of the number ? of the background ? both ?

I'm definitely not any kind of UI desgnier, so I was really trying to avoid giving suggestions :grin:.

I have a dark panel that look like this:
![PanelTopLeft_20200927](https://user-images.githubusercontent.com/71964328/94371281-30265600-00ed-11eb-8222-48a8d1801dd5.png)

In my mind, reducing background opacity of the workspace label would be the quick win. But maybe once I do that, I'd want to reduce the opacity of the number too...

But if you will only implement one, I (think I) would prefer a background opacity setting for the workspace label.
