### ISSUE TITLE
Don't show window titles on hover if "show window titles" preference is switched off

### ISSUE THREAD

**Issue by wooque** [fthx/simple-task-bar#19]
Right now when windows titles are not shown, but they appear on hover, when switching to other app, text is flickering between app name of current app, window title of hovered app you are clicking to switch to, app name of switched app, window title of switched app and it's quite annoying

**Comment by wooque** [comment]
Or maybe prevent that quick change to app name that happens when clicking on icon to switch app

**Comment by fthx** [comment]
I'll have a look at this maybe tomorrow or later in this week.

Info: I mainly work on a rewrite, with different handling of apps, maybe favorites (through a menu, because there is not enough space), and no more appmenu (just a tooltip).

**Comment by wooque** [comment]
No problem.
Thanks for your hard work :+1:
