### ISSUE TITLE
[FEATURE REQUEST] Setting to hide workspaces without active apps

### ISSUE THREAD

**Issue by jasper-jool** [fthx/simple-task-bar#2]
For example when using 2 workspaces/desktops, you would have [1] and [2] with active apps but it shows [3] as well but it has no active apps. It would be great to have an option to make it possible to hide workspaces with no active windows/apps. This would make it look even cleaner.

**Comment by fthx** [comment]
It was the case some time ago. But I decided to include the last (void) desktop to allow creating a new window in this last desktop without overview/last_desktop_thumbnail/launch_in_dash.
I let this issue open. If some others users complain too, I'll change it, it's easy.

**Comment by fthx** [comment]
Note that I won't include preferences, at least for some time. I want this extension to be simple-no-settings. :-)

**Comment by jasper-jool** [comment]
I'm okay with that :+1:

**Comment by fthx** [comment]
Hi, could you test the latest code from this github ? It has some changes ! Feedback wanted. :-) 
The Gnome extensions website is down, so...

If you do use Places Menu extension, be sure it's loaded before activating Simple Task Bar.

**Comment by fthx** [comment]
https://extensions.gnome.org/review/download/14689.shell-extension.zip

**Comment by PeterN** [comment]
I kinda like the current behaviour as it matches the standard activities view which also has a blank workspace.

**Comment by prvn-pa** [comment]
I, too don't use too many workspaces and the empty workspaces seems awkward. It would be nice if it shown only the active workspaces and apps.

**Comment by fthx** [comment]
Done !
https://github.com/fthx/simple-task-bar/commit/f3ec65eb72341b8a73a6875f76b2bed5803d088c
I'll make clean extension external settings this summer.

**Comment by fthx** [comment]
https://extensions.gnome.org/review/download/17754.shell-extension.zip
(waiting for review at the moment)
