### ISSUE TITLE
Workspace list is not update when reducing fixed workspace count

### ISSUE THREAD

**Issue by PeterN** [fthx/simple-task-bar#4]
When using the setting to have a fixed number of workspaces, if the number of workspaces is reduced the workspace list is not updated. It is then possible to click on a non-existent workspace which can cause gnome-shell to crash.

**Comment by fthx** [comment]
Ok I can reproduce, using Tweaks.

**Comment by fthx** [comment]
Ok, done. Please confirm it's solved. If not, I'll reopen this issue.
https://github.com/fthx/simple-task-bar/commit/519c244410db753a89c727ae1ed13f07ac869240
Please beware I committed this for GS 3.36 so with activities bug for you. The hack with .container causes Activties label to be shown on GS 3.36 lock screen...

So you have only to add and destroy the new signal, in the commit.
Thanks for your bug report !

**Comment by PeterN** [comment]
Yes, this works, thanks :-)

**Comment by fthx** [comment]
Ok I managed to make it work on GS 3.30 -> 3.36.
https://extensions.gnome.org/review/download/15150.shell-extension.zip
