### ISSUE TITLE
[FEATURE REQUEST] Is it possible to give the workspaces a different name?

### ISSUE THREAD

**Issue by eschrad** [fthx/simple-task-bar#6]
Like with polybar or lemonbar in tiling window managers, you could give each workspace a different name. Is that possible or perhaps in the future?

**Comment by fthx** [comment]
Well, technically it's easy. You can just change this line :
`    		this.ws_box.label.set_text((" "+(workspace_index+1)+" ").toString());`
for a conditional test `on workspace_index`.

If I go for some settings, I'll do it. I let this issue open.
BUT remember that the task bar is limited by the centre of the top panel so long names won't be fine here...

**Comment by fthx** [comment]
Done !
https://github.com/fthx/simple-task-bar/commit/f3ec65eb72341b8a73a6875f76b2bed5803d088c
I'll make clean extension external settings this summer.

**Comment by fthx** [comment]
https://extensions.gnome.org/review/download/17754.shell-extension.zip
(waiting for review at the moment)
