### ISSUE TITLE
Style update proposal

### ISSUE THREAD

**Issue by kkga** [fthx/simple-task-bar#7]
Hey! First of all: thanks for this! Coming from tiling WMs, I feel right at home with this extension :+1: 

After using it for a few hours, I realized that the visual style of workspace numbers is a bit too heavy for my taste, so I made some tweaks.

I realize that it's personal preference, but how do you feel about this direction? Would you be interested in a PR that changes these styles?

![image](https://user-images.githubusercontent.com/1460122/85716297-fe1fe500-b6f4-11ea-880e-e15805b173c9.png)

**Comment by fthx** [comment]
Hi,

Oh yes it would be nice. As you noticed, my desktop label's code isn't very complicated ;-) .
I have to check if it's fitting well on greyish panels. If not, it would be maybe necessary to add a thin border between white and your background grey.
Thanks.

**Comment by fthx** [comment]
Done by:
https://github.com/fthx/simple-task-bar/commit/bc5ac92c4978a1081d02457fd05e9b547d6aad44

I added a thin black border, barely noticeable on my dark grey panel (or Ubuntu's), not visible on the native GNOME black panel. Should avoid some issues on lighter panel's background.

I close this issue. Feel free to reopen it if my commit does not fit your needs.

Please note that I commited this here:
https://extensions.gnome.org/review/17670
but from now only for GS 3.36.

**Comment by fthx** [comment]
I changed the apps icons sizes from 22 to 20 to match the new desktops icons style (borderless):
https://github.com/fthx/simple-task-bar/commit/aa12cf21e6c09cc9032dacba12aa86a4971dc2e9
It looks better now. You can set this size in extension.js headers.
