### ISSUE TITLE
[FEATURE REQUEST] Support for multiple monitors (Dash to panel)

### ISSUE THREAD

**Issue by numeroflip** [fthx/simple-task-bar#9]
Hi, Do you know hot to display this extension on a dual monitor setting? I use the dash to panel extension, and I wish to see the simple-task-bar on both monitor's bars if possible. I made an issue on the dash-to-panel github page, but the developer said it is something better to be handled on the individual extension's side.

[This issue](https://github.com/home-sweet-gnome/dash-to-panel/issues/1109)

All i need is a labelled workspace indicator, so I forked you extension and commented out the part where you add the application icons, and modified the css to look a bit cleaner to my taste. and it looks like that: 
![image](https://user-images.githubusercontent.com/46031874/88929484-780a3780-d27a-11ea-934d-ec7956436396.png)

I know some JS but I am not familiar with how the Gnome shell works at all, so is it a hard one to achieve?
If you don't have time, but have some idea how to do it, can you share them, so I may be able to tinker around with it maybe?

Thanks for this amazing extension btw, I was searching a lot for sg like that :+1:

**Comment by fthx** [comment]
Hi,

It does not look easy, e.g. Arc Menu DtP support here : 
https://gitlab.com/arcmenu-team/Arc-Menu/-/blob/master/extension.js

I suggest you to fork my extension. Removing tasks of Simple Task Bar looks confusing. But, if some other users need this too, I can add a setting to not display tasks. I'm quite sure that few people do use the DtP taskbar with another taskbar inside. :-)

**Comment by fthx** [comment]
This feature is out of the scope of this simple extension, imho. I won't do that, it would need to create another task bar in GS.
Feel free to fork it !
